In [2]:
import torch

In [3]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [6]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [33]:
a=torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [34]:
out.backward()

In [35]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [38]:
x=torch.tensor([1,2,3],dtype=torch.float,requires_grad=True)
y=x*x*2
print(y)
print(y.grad_fn)

tensor([ 2.,  8., 18.], grad_fn=<MulBackward0>)


In [39]:
v=torch.tensor([0.1,0.01,0.001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([0.4000, 0.0800, 0.0120])
