In [1]:
import torch

x=torch.empty(5,3)
print(x)

tensor([[-4.7613e+31,  4.5586e-41, -4.7611e+31],
        [ 4.5586e-41, -4.7615e+31,  4.5586e-41],
        [-4.7615e+31,  4.5586e-41, -4.7615e+31],
        [ 4.5586e-41, -4.7616e+31,  4.5586e-41],
        [-4.7616e+31,  4.5586e-41, -4.7615e+31]])


In [3]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 1.0429,  1.5242,  0.1044],
        [-0.3345,  0.4114,  0.0102],
        [-0.7889, -0.5629, -0.0351],
        [-1.5260,  0.5492,  0.3755],
        [ 1.3718,  0.3955,  0.9131]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 1.9871,  2.2057,  0.3073],
        [ 0.4841,  1.2326,  0.5261],
        [-0.2243,  0.3539,  0.1022],
        [-1.4638,  1.2499,  0.4135],
        [ 2.1309,  1.0129,  1.3495]])


In [10]:
print(torch.add(x,y))

tensor([[ 1.9871,  2.2057,  0.3073],
        [ 0.4841,  1.2326,  0.5261],
        [-0.2243,  0.3539,  0.1022],
        [-1.4638,  1.2499,  0.4135],
        [ 2.1309,  1.0129,  1.3495]])


In [11]:
y.add_(x)
print(y)

tensor([[ 1.9871,  2.2057,  0.3073],
        [ 0.4841,  1.2326,  0.5261],
        [-0.2243,  0.3539,  0.1022],
        [-1.4638,  1.2499,  0.4135],
        [ 2.1309,  1.0129,  1.3495]])


In [12]:
print(x[:,1])

tensor([ 1.5242,  0.4114, -0.5629,  0.5492,  0.3955])


In [13]:
x=torch.rand(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x=torch.randn(2)
print(x[0].item())

1.286214828491211
